# Generated by Django 5.0.4 on 2024-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='clef_unique',
            field=models.CharField(default='Jn1jNIGVs77BwS9q', max_length=16, unique=True),
        ),
    ]
