# Generated by Django 5.0.4 on 2024-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0010_alter_utilisateur_clef_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='clef_unique',
            field=models.CharField(default='03depB4fm22T9kN3', max_length=16, unique=True),
        ),
    ]
