# Generated by Django 5.0.4 on 2024-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0014_alter_utilisateur_clef_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='clef_unique',
            field=models.CharField(default='e7FkKNxyFceARLRs', max_length=16, unique=True),
        ),
    ]
