# Generated by Django 5.0.4 on 2024-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0015_alter_utilisateur_clef_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='clef_unique',
            field=models.CharField(default='ICAnregCtSSHspOP', max_length=16, unique=True),
        ),
    ]
